// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /run/media/dpk/Nowy/code/SignalExtraction.h;
#pragma link C++ defined_in "/run/media/dpk/Nowy/code/SignalExtraction.cpp";

#endif
